# Generated by Django 3.1.13 on 2021-07-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210721_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattributes',
            name='address',
            field=models.CharField(help_text='Home Address', max_length=40),
        ),
    ]
