# Generated by Django 3.1.13 on 2021-07-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210721_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattributes',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='studentattributes',
            name='payment_status',
            field=models.BooleanField(null=True, verbose_name='Student payment status'),
        ),
        migrations.AlterField(
            model_name='studentattributes',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_allocated', to='users.room'),
        ),
        migrations.CreateModel(
            name='HostelApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.hostel')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
