# Generated by Django 3.1.13 on 2021-07-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210721_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Student College'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Student Department'),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupied',
            field=models.BooleanField(default=False, verbose_name='Is the room occupied?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_condition',
            field=models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad'), ('MAINTENANCE', 'Maintenance')], default='GOOD', max_length=50, verbose_name='Room condition'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('FULL', 'Full'), ('EMPTY', 'Empty')], default='EMPTY', max_length=50, verbose_name='Is the room full or empty'),
        ),
    ]
