# Generated by Django 3.1.13 on 2021-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210721_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='room',
        ),
        migrations.AddField(
            model_name='hostel',
            name='room_spaces',
            field=models.PositiveSmallIntegerField(default=20, max_length=70),
        ),
    ]
