# Generated by Django 3.1.13 on 2021-07-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210721_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='room_spaces',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
